"""empty message

Revision ID: 3a8b1f6b1623
Revises: 
Create Date: 2024-11-05 11:12:26.544589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b1f6b1623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('flavor', sa.String(length=80), nullable=False),
    sa.Column('allergy_concerns', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.String(length=80), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient')
    )
    op.create_table('seasonal_flavor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavor', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flavor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasonal_flavor')
    op.drop_table('ingredient')
    op.drop_table('customer_suggestion')
    # ### end Alembic commands ###
